### PR TITLE
Replace istanbul with nyc

### PR DESCRIPTION
**Pull request by TrySound**
Hi @blakeembrey. I'm here to provide esm support to all your "case" related modules.
I wasn't able to setup it with istanbul so I replace it with nyc which
has a bit more intuitive cli. Also I dropped all not supported node from travis config.

I will add esm in the next PR if you are ok with this.

### CODE REVIEW

**Comment by TrySound** [comment]
Friendly ping @blakeembrey

**Comment by TrySound** [comment]
Hi @blakeembrey do you have some time to take a look at this?

**Comment by blakeembrey** [comment]
At the moment I'm not completely interested or see the value of this change. Would you like to describe how you'd add ESM support first?

**Comment by TrySound** [comment]
Will rewrite tests and run them with [esm](https://github.com/standard-things/esm). Will distribute es module with `module` field in package.json, commonjs will be in `main` field as before. Commonjs can be generated with string.replace, or I can use rollup for this, it has very good output without `exports.default`.

My concern is rollup bundling. I use it for production build. And rollup supports only esm. Commonjs is supported with commonjs-to-esm transpiler which consumes a lot of memory. So I tend to reduce amount of commonjs-only packages.

Also browsers could run this and dependent packages with unpkg. It resolves package names and load `module` field.
https://unpkg.com/jss@10.0.0-alpha.21/dist/jss.esm.js?module

**Pull request closed without merging**
